In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("food_items.csv")

In [4]:
data.head()

,Food_items,Breakfast,Lunch,Dinner,VegNovVeg,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars,Diabetes
0,Asparagus Cooked,0,1,1,0,22,0.2,2.4,0.91,23.0,14,224.0,4.1,2.0,0,1.3,0
1,Bananas,1,0,0,0,89,0.3,1.1,0.26,5.0,1,358.0,23.0,2.6,0,12.0,1
2,Brocolli,0,1,1,0,25,0.5,3.8,1.27,118.0,56,343.0,3.1,2.8,0,0.6,0
3,Brown Rice,0,1,1,0,362,2.7,7.5,1.80,33.0,4,268.0,76.0,3.4,0,0.0,1
4,Cauliflower,0,1,1,0,32,0.3,3.0,0.72,32.0,259,278.0,6.3,3.3,0,0.0,0


In [5]:
data.describe()

,Breakfast,Lunch,Dinner,VegNovVeg,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars,Diabetes
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,0.578125,0.484375,0.789062,0.195312,248.476562,9.855469,9.428125,2.646328,51.136719,376.976562,265.932031,31.439062,3.335938,4.210938,4.647344,0.515625
std,0.495799,0.501719,0.409577,0.397999,162.466421,10.054292,8.193285,4.126727,77.424112,348.070779,169.784595,24.176263,4.092739,39.165840,10.160870,0.501719
min,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.020000,0.700000,1.000000,3.300000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000,149.000000,2.775000,4.000000,1.195000,20.000000,55.000000,149.000000,14.000000,1.650000,0.000000,0.900000,0.000000
50%,1.000000,0.000000,1.000000,0.000000,211.500000,7.750000,6.000000,2.000000,30.000000,383.000000,230.000000,25.700000,3.000000,0.000000,2.000000,1.000000
75%,1.000000,1.000000,1.000000,0.000000,307.750000,12.000000,12.500000,3.000000,40.000000,505.500000,400.000000,45.000000,4.000000,0.000000,4.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,750.000000,50.000000,30.000000,37.400000,631.000000,1531.000000,999.000000,135.000000,34.000000,435.000000,82.000000,1.000000


In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Food_items     128 non-null    object 
 1   Breakfast      128 non-null    int64  
 2   Lunch          128 non-null    int64  
 3   Dinner         128 non-null    int64  
 4   VegNovVeg      128 non-null    int64  
 5   Calories       128 non-null    int64  
 6   Fats           128 non-null    float64
 7   Proteins       128 non-null    float64
 8   Iron           128 non-null    float64
 9   Calcium        128 non-null    float64
 10  Sodium         128 non-null    int64  
 11  Potassium      128 non-null    float64
 12  Carbohydrates  128 non-null    float64
 13  Fibre          128 non-null    float64
 14  VitaminD       128 non-null    int64  
 15  Sugars         128 non-null    float64
 16  Diabetes       128 non-null    int64  
dtypes: float64(8), int64(8), object(1)
memory usage: 17.1+

In [7]:
diadata = data[data['Diabetes'] == 0]
diadata.head()

,Food_items,Breakfast,Lunch,Dinner,VegNovVeg,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars,Diabetes
0,Asparagus Cooked,0,1,1,0,22,0.2,2.4,0.91,23.0,14,224.0,4.1,2.0,0,1.3,0
2,Brocolli,0,1,1,0,25,0.5,3.8,1.27,118.0,56,343.0,3.1,2.8,0,0.6,0
4,Cauliflower,0,1,1,0,32,0.3,3.0,0.72,32.0,259,278.0,6.3,3.3,0,0.0,0
10,Cashew Nuts,1,0,0,0,553,44.0,18.0,6.68,37.0,12,660.0,30.0,3.3,0,5.9,0
11,Onions,0,1,1,0,40,0.1,1.1,0.21,23.0,4,146.0,9.3,1.7,0,4.2,0


In [8]:
diadata.info()

<class 'pandas.core.frame.DataFrame'>
Index: 62 entries, 0 to 127
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Food_items     62 non-null     object 
 1   Breakfast      62 non-null     int64  
 2   Lunch          62 non-null     int64  
 3   Dinner         62 non-null     int64  
 4   VegNovVeg      62 non-null     int64  
 5   Calories       62 non-null     int64  
 6   Fats           62 non-null     float64
 7   Proteins       62 non-null     float64
 8   Iron           62 non-null     float64
 9   Calcium        62 non-null     float64
 10  Sodium         62 non-null     int64  
 11  Potassium      62 non-null     float64
 12  Carbohydrates  62 non-null     float64
 13  Fibre          62 non-null     float64
 14  VitaminD       62 non-null     int64  
 15  Sugars         62 non-null     float64
 16  Diabetes       62 non-null     int64  
dtypes: float64(8), int64(8), object(1)
memory usage: 8.7+ KB


In [9]:
diadata.to_csv('filtered_data.csv', index=False)

In [5]:
data["Breakfast"]

0      0
1      1
2      0
3      0
4      0
      ..
123    0
124    0
125    0
126    0
127    0
Name: Breakfast, Length: 128, dtype: int64

In [89]:
Breakfastdata=data['Breakfast']
BreakfastdataNumpy=Breakfastdata.to_numpy()

Lunchdata=data['Lunch']
LunchdataNumpy=Lunchdata.to_numpy()

Dinnerdata=data['Dinner']
DinnerdataNumpy=Dinnerdata.to_numpy()

Food_itemsdata=data['Food_items']
breakfastfoodseparated=[]
Lunchfoodseparated=[]
Dinnerfoodseparated=[]

breakfastfoodseparatedID=[]
LunchfoodseparatedID=[]
DinnerfoodseparatedID=[]

for i in range(len(Breakfastdata)):
  if BreakfastdataNumpy[i]==1:
    breakfastfoodseparated.append(Food_itemsdata[i])
    breakfastfoodseparatedID.append(i)
  if LunchdataNumpy[i]==1:
    Lunchfoodseparated.append(Food_itemsdata[i])
    LunchfoodseparatedID.append(i)
  if DinnerdataNumpy[i]==1:
    Dinnerfoodseparated.append(Food_itemsdata[i])
    DinnerfoodseparatedID.append(i)

LunchfoodseparatedIDdata = data.iloc[LunchfoodseparatedID]
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.T
val=list(np.arange(5,15))
Valapnd=[0]+val
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.iloc[Valapnd]
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.T

breakfastfoodseparatedIDdata = data.iloc[breakfastfoodseparatedID]
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.T
val=list(np.arange(5,15))
Valapnd=[0]+val
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.iloc[Valapnd]
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.T


DinnerfoodseparatedIDdata = data.iloc[DinnerfoodseparatedID]
DinnerfoodseparatedIDdata=DinnerfoodseparatedIDdata.T
val=list(np.arange(5,15))
Valapnd=[0]+val
DinnerfoodseparatedIDdata=DinnerfoodseparatedIDdata.iloc[Valapnd]
DinnerfoodseparatedIDdata=DinnerfoodseparatedIDdata.T

age=21
weight=90.0
height=1.7
bmi = weight/(height**2) 
agewiseinp=0

for lp in range (0,80,20):
    test_list=np.arange(lp,lp+20)
    for i in test_list: 
        if(i == age):
            print('age is between',str(lp),str(lp+10))
            tr=round(lp/20)  
            agecl=round(lp/20)    

print("Your body mass index is: ", bmi)
if ( bmi < 16):
    print("According to your BMI.. You are severely underweight!")
    clbmi=4
elif ( bmi >= 16 and bmi < 18.5):
    print("According to your BMI.. You are underweight!")
    clbmi=3
elif ( bmi >= 18.5 and bmi < 25):
    print("According to your BMI.. You are Healthy!")
    clbmi=2
elif ( bmi >= 25 and bmi < 30):
    print("According to your BMI.. You are overweight!")
    clbmi=1
elif ( bmi >=30):
    print("According to your BMI.. You are severely overweight!")
    clbmi=0    

val1=DinnerfoodseparatedIDdata.describe()
valTog=val1.T
DinnerfoodseparatedIDdata=DinnerfoodseparatedIDdata.to_numpy()
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.to_numpy()
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.to_numpy()
ti=(bmi+agecl)/2

## K-Means Based  Dinner Food
Datacalorie=DinnerfoodseparatedIDdata[1:,1:len(DinnerfoodseparatedIDdata)]
X = np.array(Datacalorie)
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
XValu=np.arange(0,len(kmeans.labels_))
dnrlbl=kmeans.labels_

## K-Means Based  lunch Food
Datacalorie=LunchfoodseparatedIDdata[1:,1:len(LunchfoodseparatedIDdata)]
X = np.array(Datacalorie)
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
XValu=np.arange(0,len(kmeans.labels_))
lnchlbl=kmeans.labels_

## K-Means Based  lunch Food
Datacalorie=breakfastfoodseparatedIDdata[1:,1:len(breakfastfoodseparatedIDdata)]
X = np.array(Datacalorie)
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
XValu=np.arange(0,len(kmeans.labels_))
brklbl=kmeans.labels_

inp=[]
datafin=pd.read_csv('inputfin.csv')
datafin.head(5)
dataTog=datafin.T
bmicls=[0,1,2,3,4]
agecls=[0,1,2,3,4]
weightlosscat = dataTog.iloc[[1,2,7,8]]
weightlosscat=weightlosscat.T
weightgaincat= dataTog.iloc[[0,1,2,3,4,7,9,10]]
weightgaincat=weightgaincat.T
healthycat = dataTog.iloc[[1,2,3,4,6,7,9]]
healthycat=healthycat.T
weightlosscatDdata=weightlosscat.to_numpy()
weightgaincatDdata=weightgaincat.to_numpy()
healthycatDdata=healthycat.to_numpy()
weightlosscat=weightlosscatDdata[:,0:len(weightlosscatDdata)]
weightgaincat=weightgaincatDdata[:,0:len(weightgaincatDdata)]
healthycat=healthycatDdata[:,0:len(healthycatDdata)]

weightlossfin=np.zeros((len(weightlosscat)*5,6),dtype=np.float32)
weightgainfin=np.zeros((len(weightgaincat)*5,10),dtype=np.float32)
healthycatfin=np.zeros((len(healthycat)*5,9),dtype=np.float32)
t=0
r=0
s=0
yt=[]
yr=[]
ys=[]
for zz in range(5):
    for jj in range(len(weightgaincat)):
        valloc=list(weightgaincat[jj])
        valloc.append(bmicls[zz])
        valloc.append(agecls[zz])
        weightgainfin[t]=np.array(valloc)
        yt.append(brklbl[jj])
        t+=1
    for jj in range(len(weightgaincat)):
        valloc=list(weightgaincat[jj])
        valloc.append(bmicls[zz])
        valloc.append(agecls[zz])
        weightgainfin[r]=np.array(valloc)
        yr.append(lnchlbl[jj])
        r+=1
    for jj in range(len(weightgaincat)):
        valloc=list(weightgaincat[jj])
        valloc.append(bmicls[zz])
        valloc.append(agecls[zz])
        weightgainfin[s]=np.array(valloc)
        ys.append(dnrlbl[jj])
        s+=1


X_test=np.zeros((len(weightgaincat),10),dtype=np.float32)


for jj in range(len(weightgaincat)):
    valloc=list(weightgaincat[jj])
    valloc.append(agecl)
    valloc.append(clbmi)
    X_test[jj]=np.array(valloc)*ti

from sklearn.model_selection import train_test_split

val=1

if val==1:
    X_train= weightgainfin
    y_train=yt

elif val==2:
    X_train= weightgainfin
    y_train=yr 

elif val==3:
    X_train= weightgainfin
    y_train=ys


from sklearn.model_selection import train_test_split


from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier(n_estimators=100)

clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)




print ('SUGGESTED FOOD ITEMS ::')
for ii in range(len(y_pred)):
    if y_pred[ii]==2:
        print (Food_itemsdata[ii])

age is between 20 30
Your body mass index is:  31.14186851211073
According to your BMI.. You are severely overweight!


C:\Users\giris\anaconda3\envs\test\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\giris\anaconda3\envs\test\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\giris\anaconda3\envs\test\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


SUGGESTED FOOD ITEMS ::
Pumpkin
Sweet Potatoes cooked
Chia seeds
Tea


In [6]:
Breakfastdata=data['Breakfast']
BreakfastdataNumpy=Breakfastdata.to_numpy()

Lunchdata=data['Lunch']
LunchdataNumpy=Lunchdata.to_numpy()

Dinnerdata=data['Dinner']
DinnerdataNumpy=Dinnerdata.to_numpy()

Food_itemsdata=data['Food_items']

In [8]:
Food_itemsdata

0      Asparagus Cooked
1               Bananas
2              Brocolli
3            Brown Rice
4           Cauliflower
             ...       
123      Mutton Biryani
124       Prawn Biryani
125        Fish Biryani
126          Fish Curry
127           Egg Curry
Name: Food_items, Length: 128, dtype: object

In [9]:
DinnerdataNumpy

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [10]:
breakfastfoodseparated=[]
Lunchfoodseparated=[]
Dinnerfoodseparated=[]

breakfastfoodseparatedID=[]
LunchfoodseparatedID=[]
DinnerfoodseparatedID=[]

for i in range(len(Breakfastdata)):
  if BreakfastdataNumpy[i]==1:
    breakfastfoodseparated.append(Food_itemsdata[i])
    breakfastfoodseparatedID.append(i)
  if LunchdataNumpy[i]==1:
    Lunchfoodseparated.append(Food_itemsdata[i])
    LunchfoodseparatedID.append(i)
  if DinnerdataNumpy[i]==1:
    Dinnerfoodseparated.append(Food_itemsdata[i])
    DinnerfoodseparatedID.append(i)

In [20]:
LunchfoodseparatedIDdata = data.iloc[LunchfoodseparatedID]
LunchfoodseparatedIDdata = LunchfoodseparatedIDdata.T
val=list(np.arange(5,17))
Valapnd=[0]+[4]+val
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.iloc[Valapnd]
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.T

In [21]:
LunchfoodseparatedIDdata

,Food_items,VegNovVeg,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars,Diabetes
0,Asparagus Cooked,0,22,0.2,2.4,0.91,23.0,14,224.0,4.1,2.0,0,1.3,0
2,Brocolli,0,25,0.5,3.8,1.27,118.0,56,343.0,3.1,2.8,0,0.6,0
3,Brown Rice,0,362,2.7,7.5,1.8,33.0,4,268.0,76.0,3.4,0,0.0,1
4,Cauliflower,0,32,0.3,3.0,0.72,32.0,259,278.0,6.3,3.3,0,0.0,0
6,Corn,0,97,1.4,3.3,0.55,2.0,253,3.3,22.0,2.7,0,7.7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Mutton Biryani,1,600,25.0,30.0,4.0,40.0,900,500.0,50.0,4.0,0,4.0,1
124,Prawn Biryani,1,600,25.0,30.0,4.0,40.0,900,500.0,50.0,4.0,0,4.0,1
125,Fish Biryani,1,600,25.0,30.0,4.0,40.0,900,500.0,50.0,4.0,0,4.0,1
126,Fish Curry,1,250,15.0,20.0,2.0,40.0,900,500.0,10.0,2.0,0,3.0,1


In [22]:
breakfastfoodseparatedIDdata = data.iloc[breakfastfoodseparatedID]
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.T
val=list(np.arange(5,17))
Valapnd=[0]+[4]+val
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.iloc[Valapnd]
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.T

DinnerfoodseparatedIDdata = data.iloc[DinnerfoodseparatedID]
DinnerfoodseparatedIDdata=DinnerfoodseparatedIDdata.T
val=list(np.arange(5,17))
Valapnd=[0]+[4]+val
DinnerfoodseparatedIDdata=DinnerfoodseparatedIDdata.iloc[Valapnd]
DinnerfoodseparatedIDdata=DinnerfoodseparatedIDdata.T

In [23]:
breakfastfoodseparatedIDdata

,Food_items,VegNovVeg,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars,Diabetes
1,Bananas,0,89,0.3,1.1,0.26,5.0,1,358.0,23.0,2.6,0,12.0,1
5,Coffee,0,2,0.0,0.3,0.02,2.0,1,50.0,0.2,0.0,0,0.0,1
6,Corn,0,97,1.4,3.3,0.55,2.0,253,3.3,22.0,2.7,0,7.7,1
8,Grapes,0,93,2.1,5.6,2.63,363.0,9,272.0,17.0,11.0,0,6.3,1
9,Milk,0,97,6.9,3.8,0.12,169.0,52,178.0,5.2,0.0,0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Onion Rava Dosa,0,200,8.0,5.0,2.0,20.0,400,100.0,30.0,3.0,0,2.0,0
97,Bisi Bele Bath,0,400,12.0,10.0,3.0,40.0,700,250.0,60.0,6.0,0,3.0,0
98,Tomato Bath,0,300,12.0,6.0,3.0,30.0,400,100.0,45.0,3.0,0,3.0,0
99,Paniyaram,0,150,5.0,4.0,2.0,20.0,300,100.0,20.0,2.0,0,2.0,0


In [24]:
DinnerfoodseparatedIDdata

,Food_items,VegNovVeg,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars,Diabetes
0,Asparagus Cooked,0,22,0.2,2.4,0.91,23.0,14,224.0,4.1,2.0,0,1.3,0
2,Brocolli,0,25,0.5,3.8,1.27,118.0,56,343.0,3.1,2.8,0,0.6,0
3,Brown Rice,0,362,2.7,7.5,1.8,33.0,4,268.0,76.0,3.4,0,0.0,1
4,Cauliflower,0,32,0.3,3.0,0.72,32.0,259,278.0,6.3,3.3,0,0.0,0
6,Corn,0,97,1.4,3.3,0.55,2.0,253,3.3,22.0,2.7,0,7.7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Mutton Biryani,1,600,25.0,30.0,4.0,40.0,900,500.0,50.0,4.0,0,4.0,1
124,Prawn Biryani,1,600,25.0,30.0,4.0,40.0,900,500.0,50.0,4.0,0,4.0,1
125,Fish Biryani,1,600,25.0,30.0,4.0,40.0,900,500.0,50.0,4.0,0,4.0,1
126,Fish Curry,1,250,15.0,20.0,2.0,40.0,900,500.0,10.0,2.0,0,3.0,1


In [25]:
age=21
weight=70.0
height=1.7
bmi = weight/(height**2) 

In [26]:
bmi

24.221453287197235

In [28]:
for lp in range (0,80,20):
    test_list=np.arange(lp,lp+20)
    for i in test_list: 
        if(i == age):
            print('age is between',str(lp),str(lp+10))
            agecl=round(lp/20)  
            
agecl

age is between 20 30


1

In [30]:
print("Your body mass index is: ", bmi)
if ( bmi < 16):
    print("You are severely underweight")
    clbmi=4
elif ( bmi >= 16 and bmi < 18.5):
    print("You are underweight")
    clbmi=3
elif ( bmi >= 18.5 and bmi < 25):
    print("You are Healthy")
    clbmi=2
elif ( bmi >= 25 and bmi < 30):
    print("You are overweight")
    clbmi=1
elif ( bmi >=30):
    print("You are severely overweight")
    clbmi=0

clbmi

Your body mass index is:  24.221453287197235
You are Healthy


2

In [31]:
DinnerfoodseparatedIDdata=DinnerfoodseparatedIDdata.to_numpy()
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.to_numpy()
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.to_numpy()
ti=(clbmi+agecl)/2
ti

1.5

In [32]:
DinnerfoodseparatedIDdata

array([['Asparagus Cooked', 0, 22, ..., 0, 1.3, 0],
       ['Brocolli', 0, 25, ..., 0, 0.6, 0],
       ['Brown Rice', 0, 362, ..., 0, 0.0, 1],
       ...,
       ['Fish Biryani', 1, 600, ..., 0, 4.0, 1],
       ['Fish Curry', 1, 250, ..., 0, 3.0, 1],
       ['Egg Curry', 1, 250, ..., 0, 3.0, 0]], dtype=object)

13

In [45]:
from sklearn.cluster import KMeans

## K-Means Based  Dinner Food
Datacalorie=DinnerfoodseparatedIDdata[:,1:len(DinnerfoodseparatedIDdata[0])-1]
Datacalorie

array([[0, 22, 0.2, ..., 2.0, 0, 1.3],
       [0, 25, 0.5, ..., 2.8, 0, 0.6],
       [0, 362, 2.7, ..., 3.4, 0, 0.0],
       ...,
       [1, 600, 25.0, ..., 4.0, 0, 4.0],
       [1, 250, 15.0, ..., 2.0, 0, 3.0],
       [1, 250, 15.0, ..., 2.0, 0, 3.0]], dtype=object)

In [46]:
X = np.array(Datacalorie)
X

array([[0, 22, 0.2, ..., 2.0, 0, 1.3],
       [0, 25, 0.5, ..., 2.8, 0, 0.6],
       [0, 362, 2.7, ..., 3.4, 0, 0.0],
       ...,
       [1, 600, 25.0, ..., 4.0, 0, 4.0],
       [1, 250, 15.0, ..., 2.0, 0, 3.0],
       [1, 250, 15.0, ..., 2.0, 0, 3.0]], dtype=object)

In [48]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
XValu=np.arange(0,len(kmeans.labels_))
dnrlbl=kmeans.labels_
dnrlbl

C:\Users\giris\anaconda3\envs\test\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 1, 2, 1, 0, 0, 0,
       0, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2,
       1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
## K-Means Based  Lunch Food
Datacalorie=LunchfoodseparatedIDdata[1:,1:len(LunchfoodseparatedIDdata[0])-1]
X = np.array(Datacalorie)
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
XValu=np.arange(0,len(kmeans.labels_))
lnchlbl=kmeans.labels_

## K-Means Based  Breakfast Food
Datacalorie=breakfastfoodseparatedIDdata[1:,1:len(breakfastfoodseparatedIDdata[0])-1]
X = np.array(Datacalorie)
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
XValu=np.arange(0,len(kmeans.labels_))
brklbl=kmeans.labels_

C:\Users\giris\anaconda3\envs\test\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\giris\anaconda3\envs\test\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [68]:

## Reading of the Dataset
datafin=pd.read_csv('inputfin.csv')

dataTog=datafin.T
dataTog.head()

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0Calories,160.00,89.00,349.0,331.00,2.00,97.00,93.00,97.00,553.00,97.0,...,384.0,1.00,52.00,32.00,120.00,350.00,550.0,519.00,304.00,535.00
1Fats (gm),15.00,0.30,0.4,24.00,0.00,1.40,2.10,6.90,44.00,0.2,...,0.9,0.00,0.20,0.30,1.90,22.00,50.0,34.00,0.00,30.00
2Proteins(g),2.00,1.10,14.0,20.00,0.30,3.30,5.60,3.80,18.00,1.5,...,5.9,0.00,0.30,0.70,4.40,4.30,22.0,2.30,0.30,7.70
3Iron(mg),0.55,0.26,6.8,0.84,0.02,0.55,2.63,0.12,6.68,0.8,...,19.4,0.08,0.12,0.41,1.49,0.75,3.4,1.25,0.42,2.35
4Calcium(mg),12.00,5.00,190.0,497.00,2.00,2.00,2.00,2.00,2.00,2.0,...,2.0,2.00,2.00,2.00,2.00,2.00,2.0,2.00,2.00,2.00


In [69]:
bmicls=[0,1,2,3,4]
agecls=[0,1,2,3,4]

weightlosscat = dataTog.iloc[[1,2,7,8]]
weightlosscat=weightlosscat.T
weightlosscat

,1Fats (gm),2Proteins(g),7Carbohydrates (gm),8Fibre (gm)
0,15.0,2.0,8.5,6.7
1,0.3,1.1,8.5,2.6
2,0.4,14.0,8.5,13.0
3,24.0,20.0,8.5,0.0
4,0.0,0.3,8.5,0.0
5,1.4,3.3,8.5,2.7
6,2.1,5.6,8.5,11.0
7,6.9,3.8,8.5,0.0
8,44.0,18.0,8.5,3.3
9,0.2,1.5,8.5,11.0


In [70]:
weightgaincat= dataTog.iloc[[0,1,2,3,4,7,9,10]]
weightgaincat=weightgaincat.T
weightgaincat

,0Calories,1Fats (gm),2Proteins(g),3Iron(mg),4Calcium(mg),7Carbohydrates (gm),9Vitamin D (mcg),10Sugars (gm)
0,160.0,15.0,2.0,0.55,12.0,8.5,0.0,0.70
1,89.0,0.3,1.1,0.26,5.0,8.5,0.0,12.00
2,349.0,0.4,14.0,6.80,190.0,8.5,0.0,46.00
3,331.0,24.0,20.0,0.84,497.0,8.5,0.0,0.00
4,2.0,0.0,0.3,0.02,2.0,8.5,0.0,0.00
5,97.0,1.4,3.3,0.55,2.0,8.5,0.0,7.70
6,93.0,2.1,5.6,2.63,2.0,8.5,0.0,6.30
7,97.0,6.9,3.8,0.12,2.0,8.5,0.0,0.00
8,553.0,44.0,18.0,6.68,2.0,8.5,0.0,5.90
9,97.0,0.2,1.5,0.80,2.0,8.5,0.0,0.00


In [71]:
healthycat = dataTog.iloc[[1,2,3,4,6,7,9]]
healthycat=healthycat.T
healthycat

,1Fats (gm),2Proteins(g),3Iron(mg),4Calcium(mg),6Potassium(mg),7Carbohydrates (gm),9Vitamin D (mcg)
0,15.0,2.0,0.55,12.0,485.0,8.5,0.0
1,0.3,1.1,0.26,5.0,358.0,8.5,0.0
2,0.4,14.0,6.80,190.0,77.0,8.5,0.0
3,24.0,20.0,0.84,497.0,363.0,8.5,0.0
4,0.0,0.3,0.02,2.0,50.0,8.5,0.0
5,1.4,3.3,0.55,2.0,3.3,8.5,0.0
6,2.1,5.6,2.63,2.0,272.0,8.5,0.0
7,6.9,3.8,0.12,2.0,178.0,8.5,0.0
8,44.0,18.0,6.68,2.0,660.0,8.5,0.0
9,0.2,1.5,0.80,2.0,212.0,8.5,0.0


In [72]:
weightlosscatDdata=weightlosscat.to_numpy()
weightgaincatDdata=weightgaincat.to_numpy()
healthycatDdata=healthycat.to_numpy()
weightlosscat=weightlosscatDdata[:,0:len(weightlosscatDdata)]
weightgaincat=weightgaincatDdata[:,0:len(weightgaincatDdata)]
healthycat=healthycatDdata[:,0:len(healthycatDdata)]

In [73]:
healthycat

array([[1.500e+01, 2.000e+00, 5.500e-01, 1.200e+01, 4.850e+02, 8.500e+00,
        0.000e+00],
       [3.000e-01, 1.100e+00, 2.600e-01, 5.000e+00, 3.580e+02, 8.500e+00,
        0.000e+00],
       [4.000e-01, 1.400e+01, 6.800e+00, 1.900e+02, 7.700e+01, 8.500e+00,
        0.000e+00],
       [2.400e+01, 2.000e+01, 8.400e-01, 4.970e+02, 3.630e+02, 8.500e+00,
        0.000e+00],
       [0.000e+00, 3.000e-01, 2.000e-02, 2.000e+00, 5.000e+01, 8.500e+00,
        0.000e+00],
       [1.400e+00, 3.300e+00, 5.500e-01, 2.000e+00, 3.300e+00, 8.500e+00,
        0.000e+00],
       [2.100e+00, 5.600e+00, 2.630e+00, 2.000e+00, 2.720e+02, 8.500e+00,
        0.000e+00],
       [6.900e+00, 3.800e+00, 1.200e-01, 2.000e+00, 1.780e+02, 8.500e+00,
        0.000e+00],
       [4.400e+01, 1.800e+01, 6.680e+00, 2.000e+00, 6.600e+02, 8.500e+00,
        0.000e+00],
       [2.000e-01, 1.500e+00, 8.000e-01, 2.000e+00, 2.120e+02, 8.500e+00,
        0.000e+00],
       [1.000e-01, 4.000e-01, 1.800e-01, 2.000e+00, 1.160e+0

In [74]:
weightlossfin=np.zeros((len(weightlosscat)*5,6),dtype=np.float32)
weightgainfin=np.zeros((len(weightgaincat)*5,10),dtype=np.float32)
healthycatfin=np.zeros((len(healthycat)*5,9),dtype=np.float32)

In [75]:
weightlossfin

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

In [82]:
t=0
r=0
s=0
yt=[]
yr=[]
ys=[]

for zz in range(5):
    for jj in range(len(weightlosscat)):
        valloc=list(weightlosscat[jj])
        valloc.append(bmicls[zz])
        valloc.append(agecls[zz])
        weightlossfin[t]=np.array(valloc)
        yt.append(brklbl[jj])
        t+=1

    for jj in range(len(weightlosscat)):
        valloc=list(weightlosscat[jj])
        valloc.append(bmicls[zz])
        valloc.append(agecls[zz])
        weightlossfin[r]=np.array(valloc)
        yr.append(lnchlbl[jj])
        r+=1

    for jj in range(len(weightlosscat)):
        valloc=list(weightlosscat[jj])
        valloc.append(bmicls[zz])
        valloc.append(agecls[zz])
        weightlossfin[s]=np.array(valloc)
        ys.append(dnrlbl[jj])
        s+=1

X_test=np.zeros((len(weightlosscat),6),dtype=np.float32)


In [83]:
for jj in range(len(weightlosscat)):
    valloc=list(weightlosscat[jj])
    valloc.append(agecl)
    valloc.append(clbmi)
    X_test[jj]=np.array(valloc)*ti
    
X_test

array([[22.5 ,  3.  , 12.75, 10.05,  1.5 ,  3.  ],
       [ 0.45,  1.65, 12.75,  3.9 ,  1.5 ,  3.  ],
       [ 0.6 , 21.  , 12.75, 19.5 ,  1.5 ,  3.  ],
       [36.  , 30.  , 12.75,  0.  ,  1.5 ,  3.  ],
       [ 0.  ,  0.45, 12.75,  0.  ,  1.5 ,  3.  ],
       [ 2.1 ,  4.95, 12.75,  4.05,  1.5 ,  3.  ],
       [ 3.15,  8.4 , 12.75, 16.5 ,  1.5 ,  3.  ],
       [10.35,  5.7 , 12.75,  0.  ,  1.5 ,  3.  ],
       [66.  , 27.  , 12.75,  4.95,  1.5 ,  3.  ],
       [ 0.3 ,  2.25, 12.75, 16.5 ,  1.5 ,  3.  ],
       [ 0.15,  0.6 , 12.75,  4.65,  1.5 ,  3.  ],
       [25.5 , 69.  , 12.75, 10.65,  1.5 ,  3.  ],
       [ 2.1 ,  3.  , 12.75,  3.75,  1.5 ,  3.  ],
       [14.25, 19.5 , 12.75, 21.  ,  1.5 ,  3.  ],
       [ 5.55,  6.75, 12.75,  1.35,  1.5 ,  3.  ],
       [ 2.55,  7.5 , 12.75,  3.15,  1.5 ,  3.  ],
       [ 2.25,  3.9 , 12.75,  1.65,  1.5 ,  3.  ],
       [ 0.3 ,  1.8 , 12.75,  1.35,  1.5 ,  3.  ],
       [ 6.  ,  4.65, 12.75,  0.  ,  1.5 ,  3.  ],
       [ 9.3 ,  6.6 , 12.75,  4

In [84]:
from sklearn.model_selection import train_test_split
val=1

if val==1:
    X_train= weightlossfin
    y_train=yt

elif val==2:
    X_train= weightlossfin
    y_train=yr 

elif val==3:
    X_train= weightlossfin
    y_train=ys

In [85]:

from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier(n_estimators=100)

clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)


print ('SUGGESTED FOOD ITEMS ::')
for ii in range(len(y_pred)):
    if y_pred[ii]==2:
        print (Food_itemsdata[ii])

SUGGESTED FOOD ITEMS ::
Brocolli
Pears
Orange juice
Salmon
Beans
Apples
